# Generated by Django 6.0.1 on 2026-07-24 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(default="", max_length=30)),
                ("last_name", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("clinician", "Clinician"), ("admin", "Admin")],
                        default="clinician",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Horse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("breed", models.CharField(blank=True, default="", max_length=120)),
                ("colour", models.CharField(blank=True, default="", max_length=120)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "horse_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("gait", models.CharField(blank=True, default="Trot", max_length=30)),
                ("notes", models.TextField(blank=True, default="")),
                ("video", models.FileField(upload_to="uploads/videos/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "annotated_video",
                    models.FileField(
                        blank=True, null=True, upload_to="annotated_videos/"
                    ),
                ),
                (
                    "tracking_mode",
                    models.CharField(
                        choices=[("yolo26", "YOLO26 Pose"), ("classical", "Classical")],
                        default="yolo26",
                        max_length=20,
                    ),
                ),
                (
                    "classical_submode",
                    models.CharField(
                        blank=True,
                        choices=[("markerless", "Markerless"), ("markers", "Markers")],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                (
                    "orientation",
                    models.CharField(blank=True, default="unknown", max_length=50),
                ),
                (
                    "visible_side",
                    models.CharField(blank=True, default="unknown", max_length=20),
                ),
                ("fps", models.FloatField(default=30.0)),
                ("total_frames", models.PositiveIntegerField(default=0)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("symmetry_index", models.FloatField(blank=True, null=True)),
                ("narrative_report", models.TextField(blank=True)),
                ("poll_rom_norm", models.FloatField(blank=True, null=True)),
                ("wither_rom_norm", models.FloatField(blank=True, null=True)),
                ("pelvis_rom_norm", models.FloatField(blank=True, null=True)),
                ("pelvis_roll_mean_abs_norm", models.FloatField(blank=True, null=True)),
                (
                    "fore_protraction_asymmetry_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "hind_protraction_asymmetry_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("summary_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "manual_start_frame",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("manual_keypoints_norm", models.JSONField(blank=True, default=list)),
                ("manual_keyframes_norm", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "horse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="users.horse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionAngleFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_index", models.PositiveIntegerField()),
                ("timestamp_sec", models.FloatField()),
                ("keypoints_norm", models.JSONField(blank=True, default=list)),
                ("bbox_xyxy_norm", models.JSONField(blank=True, default=list)),
                ("frame_quality_score", models.FloatField(blank=True, null=True)),
                (
                    "orientation",
                    models.CharField(blank=True, default="unknown", max_length=50),
                ),
                (
                    "visible_side",
                    models.CharField(blank=True, default="unknown", max_length=20),
                ),
                ("left_hip_angle_deg", models.FloatField(blank=True, null=True)),
                ("left_stifle_angle_deg", models.FloatField(blank=True, null=True)),
                ("left_hock_angle_deg", models.FloatField(blank=True, null=True)),
                (
                    "left_hind_fetlock_angle_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("left_shoulder_angle_deg", models.FloatField(blank=True, null=True)),
                ("left_elbow_angle_deg", models.FloatField(blank=True, null=True)),
                ("left_knee_angle_deg", models.FloatField(blank=True, null=True)),
                (
                    "left_fore_fetlock_angle_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("right_hip_angle_deg", models.FloatField(blank=True, null=True)),
                ("right_stifle_angle_deg", models.FloatField(blank=True, null=True)),
                ("right_hock_angle_deg", models.FloatField(blank=True, null=True)),
                (
                    "right_hind_fetlock_angle_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("right_shoulder_angle_deg", models.FloatField(blank=True, null=True)),
                ("right_elbow_angle_deg", models.FloatField(blank=True, null=True)),
                ("right_knee_angle_deg", models.FloatField(blank=True, null=True)),
                (
                    "right_fore_fetlock_angle_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "left_hind_protraction_signed_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "left_fore_protraction_signed_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "right_hind_protraction_signed_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "right_fore_protraction_signed_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("left_hind_protraction_deg", models.FloatField(blank=True, null=True)),
                ("left_fore_protraction_deg", models.FloatField(blank=True, null=True)),
                (
                    "right_hind_protraction_deg",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "right_fore_protraction_deg",
                    models.FloatField(blank=True, null=True),
                ),
                ("poll_y_norm", models.FloatField(blank=True, null=True)),
                ("wither_y_norm", models.FloatField(blank=True, null=True)),
                ("pelvis_mid_y_norm", models.FloatField(blank=True, null=True)),
                ("head_mid_y_norm", models.FloatField(blank=True, null=True)),
                ("left_pelvis_y_norm", models.FloatField(blank=True, null=True)),
                ("right_pelvis_y_norm", models.FloatField(blank=True, null=True)),
                ("pelvis_roll_diff_norm", models.FloatField(blank=True, null=True)),
                ("tail_base_y_norm", models.FloatField(blank=True, null=True)),
                ("metrics_json", models.JSONField(blank=True, default=dict)),
                (
                    "tracking_source",
                    models.CharField(blank=True, default="yolo26", max_length=20),
                ),
                ("keypoint_confidences", models.JSONField(blank=True, default=list)),
                ("keypoint_tracking_meta", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="users.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["frame_index"],
                "unique_together": {("session", "frame_index")},
            },
        ),
    ]
